### PR TITLE
Add Searching Algorithms

### PR DESCRIPTION
**Pull request by devaaravmishra**

### CODE REVIEW

**Comment by Harsh-jot** [comment]
Good Program🙌🏻
Should add few more

**Review by ayusshrathore — APPROVED** [review]

**Review by ayusshrathore — APPROVED** [review]
Nice. Clean and concise code. Appreciate how you made methods for every search algorithm.

**Comment by devaaravmishra** [comment]
@ayusshrathore thanks for the compliment, btw nice contribution from you too...

**Comment by devaaravmishra** [comment]
@Harsh-jot Made the necessary changes hoping for a merge this time!

**Pull request merged**
